- name: Create Azure VM for pterodactyl Wings
  hosts: localhost
  connection: local
  tasks:
  - name: Create MySQL Server
    azure_rm_mysqlserver:
      resource_group: PedroTactile
      name: MyPedroSQLServ
      sku:
        name: B_Gen5_1
        tier: Basic
      location: francecentral
      enforce_ssl: yes
      version: 8.0
      admin_username: pterodactyl
      admin_password: MotDeP3dro!
  - name: Create instance of MySQL Database
    
    azure_rm_mysqldatabase:
      resource_group: PedroTactile
      server_name: MyPedroSQLServ
      name: pterodactyl

  - name: Create (or update) MySQL firewall rule
    azure_rm_mysqlfirewallrule:
      resource_group: PedroTactile
      server_name: MyPedroSQLServ
      name: ip_simplon
      start_ip_address: 212.51.190.22
      end_ip_address: 212.51.190.22
  
  - name: Create user with password, all database privileges and 'WITH GRANT OPTION' in pterodactyl
    community.mysql.mysql_user:
      login_user: pterodactyl@mypedrosqlserv
      login_password: MotDeP3dro!
      host: mypedrosqlserv
      login_host: mypedrosqlserv.mysql.database.azure.com
      check_hostname: yes
      state: present
      name: pterodactyluser
      password: MotDeP3dro!
      priv:
        'pterodactyl.*': 'ALL,GRANT'