- name: Create Azure VM for pterodactyl Wings
  hosts: localhost
  connection: local
  tasks:
  - name: Create MySQL Server
    azure_rm_mysqlserver:
      resource_group: PedroTactile
      name: MyPedroSQLServ
      sku:
        name: B_Gen5_1
        tier: Basic
      location: francecentral
      version: 8.0
      enforce_ssl: True
      admin_username: pterodactyl
      admin_password: MotDeP3dro!
  - name: Create instance of MySQL Database
    
    azure_rm_mysqldatabase:
      resource_group: PedroTactile
      server_name: MyPedroSQLServ
      name: pterodactyl
  
  - name: Create user with password, all database privileges and 'WITH GRANT OPTION' in pterodactyl
    community.mysql.mysql_user:
      state: present
      name: pterodactyluser
      password: MotDeP3dro!
      priv:
        'pterodactyl.*': 'ALL,GRANT'

  - name: Create Azure Cache for Redis
    azure_rm_rediscache:
      resource_group: PedroTactile
      name: pedroCache
      sku:
        name: basic
        size: C1

  - name: Wait for Redis provisioning to complete
    azure_rm_rediscache_info:
      resource_group: PedroTactile
      name: pedroCache
    register: facts
    until: "{{ facts.rediscaches[0]['provisioning_state'] == 'Succeeded' }}"
    retries: 100
    delay: 60