- name: Create Azure panel container
  hosts: localhost
  connection: local
  tasks:
  - name: Create sample container group with git repo volume
    azure_rm_containerinstance:
      resource_group: PedroTactile
      name: PedroPanel
      os_type: linux
      ip_address: public
      dns_name_label: PedroPanel
      containers:
        - name: PedroContainer
          image: aeonlucid/pterodactyl-panel
          cpu: 1
          memory: 1
          environment_variables:
            - name: PUID
              value: PUID=1000
            - name: PGID
              value: PGID=1000
            - name: creat_admin
              value: CREATE_ADMIN=yes
          volume_mounts:
            - name: pedroData
              mount_path: "/data"
          ports:
            - 8080
      volumes:
        - name: filesharevolume
          azure_file:
            storage_account_name: mystorageaccount
            share_name: acishare
            storage_account_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

