- name: Create Azure panel container
  hosts: localhost
  connection: local
  tasks:
  - name: Create sample container group with git repo volum
    azure_rm_containerinstance:
      resource_group: PedroTactile
      name: PedroPanel
      os_type: linux
      ip_address: public
      dns_name_label: PedroPanel
      containers:
        - name: PedroContainer
          image: httpdaeonlucid/pterodactyl-panel
          cpu: 1
          memory: 1
          volume_mounts:
            - name: myvolume1
              mount_path: "/mnt/test"
          ports:
            - 80
            - 81
      volumes:
        - name: filesharevolume
          azure_file:
            storage_account_name: mystorageaccount
            share_name: acishare
            storage_account_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

