- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: PedroTactile
      location: francecentral

  - name: Create virtual network
    azure.azcollection.azure_rm_virtualnetwork:
      resource_group: PedroTactile
      name: virtualPedroNetwork
      address_prefixes: "10.10.0.0/16"

  - name: Add subnet
    azure.azcollection.azure_rm_subnet:
      resource_group: PedroTactile
      name: subnetPedro
      address_prefix: "10.10.0.0/29"
      virtual_network: virtualPedroNetwork

  - name: Add subnet
    azure.azcollection.azure_rm_subnet:
      resource_group: PedroTactile
      name: subnetGateway
      address_prefix: "10.10.1.0/29"
      virtual_network: virtualPedroNetwork

  - name: Create public ip
    azure.azcollection.azure_rm_publicipaddress:
      resource_group: PedroTactile
      allocation_method: Static
      name: pedroIpBastion
    register: output_ip_address_bastion    
  - name: Public IP of VM
    debug:
      msg: "The public IP for the Bastion is {{ output_ip_address_bastion.state.ip_address }}."
  
  - name: Create public ip
    azure.azcollection.azure_rm_publicipaddress:
      resource_group: PedroTactile
      allocation_method: Static
      name: pedroIpAppli
    register: output_ip_address_Appli   
  - name: Public IP of VM
    debug:
      msg: "The public IP for the appli is {{ output_ip_address_Appli.state.ip_address }}."