- name: Create Azure VM for pterodactyl Wings
  hosts: localhost
  connection: local
  tasks:
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: PedroTactile
      name: PedroWingsNSG
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 22
          access: Allow
          priority: 1001
          direction: Inbound
  - name: Create virtual network interface card
    azure_rm_networkinterface:
      resource_group: PedroTactile
      name: NICe_Marseille
      virtual_network: virtualPedroNetwork
      subnet: subnetAppli
      public_ip_name: pedroIpAppli
      security_group: PedroWingsNSG
  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: PedroTactile
      name: PedroWingsVM
      vm_size: Standard_B2s
      admin_username: pedro
      ssh_password_enabled: false
      ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "<key_data>"
      network_interfaces: NICe_Marseille
      image:
        offer: debian-10
        publisher: Debian
        sku: '10'
        version: latest
