- name: Create Azure application gatway
  hosts: localhost
  connection: local
  tasks:
  - name: Get facts subnetag
    azure_rm_subnet_info:
      resource_group: PedroTactile
      virtual_network_name: virtualPedroNetwork
      name: subnetag
    register: subnetaginfo
  - name: debug subnet infos
    debug:
      msg: "{{ subnetaginfo.subnets[0].id }}"  

  - name: Get specific Container Instance facts
    azure_rm_networkinterface_info:
      resource_group: PedroTactile
      name: PedroPanelNIC
    register: PedroPanel

  - name: debug Container instance
    debug:
      msg: "{{ PedroPanel.networkinterfaces[0].ip_configurations[0].private_ip_address }}"
  
  - name: Create instance of Application Gateway
    azure_rm_appgateway:
      resource_group: PedroTactile
      name: pedroag
      sku:
        name: standard_v2
        tier: standard_v2
        capacity: 2
      gateway_ip_configurations:
        - subnet:
            id: "{{ subnetaginfo.subnets[0].id }}"
          name: gatewayip      
      frontend_ip_configurations:
        - public_ip_address:  IPdroPanel
          name: sample_gateway_frontend_ip_config
      frontend_ports:
        - port: 80
          name: ag_frontend_pedroport
      backend_address_pools:
        - backend_addresses:
            - ip_address: "{{ PedroPanel.networkinterfaces[0].ip_configurations[0].private_ip_address }}"
          name: backend_pool_pedrocontainer
      backend_http_settings_collection:
        - port: 80
          protocol: http
          cookie_based_affinity: enabled
          name: sample_appgateway_http_settings
      http_listeners:
        - frontend_ip_configuration: sample_gateway_frontend_ip_config
          frontend_port: ag_frontend_pedroport
          name: sample_http_listener
      request_routing_rules:
        - rule_type: standard
          backend_address_pool: backend_pool_pedrocontainer
          backend_http_settings: sample_appgateway_http_settings
          http_listener: sample_http_listener
          name: rule1