- name: Création infra basique
  hosts: localhost
  connection: local
  tasks:
  - name: Création du resource group PedroTactileⒸ
    azure_rm_resourcegroup:
      name: PedroTactile
      location: francecentral

  - name: Création du VNet
    azure.azcollection.azure_rm_virtualnetwork:
      resource_group: PedroTactile
      name: virtualPedroNetwork
      address_prefixes: "10.10.0.0/16"

  - name: Ajout du subnet Bastion
    azure.azcollection.azure_rm_subnet:
      resource_group: PedroTactile
      name: subnetPedro
      address_prefix: "10.10.0.0/24"
      virtual_network: virtualPedroNetwork

  - name: Ajout du subnet LoadBalancer - est-ce vraiment utile ?
    azure.azcollection.azure_rm_subnet:
      resource_group: PedroTactile
      name: subnetLB
      address_prefix: "10.10.1.0/24"
      virtual_network: virtualPedroNetwork

  - name: Création ip publique vm PedroBastion
    azure.azcollection.azure_rm_publicipaddress:
      resource_group: PedroTactile
      allocation_method: Static
      name: pedroIpBastion
    register: output_ip_address_bastion    
  - name: Public IP of VM
    debug:
      msg: "The public IP for the Bastion is {{ output_ip_address_bastion.state.ip_address }}."
  
  - name: Création ip publique test PedroIpAppli
    azure.azcollection.azure_rm_publicipaddress:
      resource_group: PedroTactile
      allocation_method: Static
      name: pedroIpAppli
    register: output_ip_address_Appli   
  - name: Public IP of VM
    debug:
      msg: "The public IP for the appli is {{ output_ip_address_Appli.state.ip_address }}."

  - name: Création nsg autorisant ssh
    azure_rm_securitygroup:
      resource_group: PedroTactile
      name: PedroBastionNSG
      rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound

  # - name: Création NIC pour vm test PedroBastion
  #   azure_rm_networkinterface:
  #     resource_group: PedroTactile
  #     name: PedroBastionNIC
  #     virtual_network: virtualPedroNetwork
  #     subnet: subnetLB
  #     public_ip_name: pedroIpBastion
  #     security_group: PedroBastionNSG

  - name: Création nsg autorisant ssh pour vm test PedroAppli
    azure_rm_securitygroup:
      resource_group: PedroTactile
      name: PedroBastionNSG2
      rules:
      - name: SSH
        protocol: Tcp
        destination_port_range: 22
        access: Allow
        priority: 101
        direction: Inbound

  # - name: Création NIC pour vm test PedroAppli
  #   azure_rm_networkinterface:
  #     resource_group: PedroTactile
  #     name: PedroBastionNIC2
  #     virtual_network: virtualPedroNetwork
  #     subnet: subnetLB
  #     public_ip_name: pedroIpAppli
  #     security_group: PedroBastionNSG2

# - name: Création VM Bastion
#   hosts: localhost
#   connection: local
#   tasks:

#   - name: Create VM
#     azure_rm_virtualmachine:
#       resource_group: PedroTactile
#       name: PedroBastion
#       vm_size: Standard_B1ls
#       admin_username: pedro
#       ssh_password_enabled: false
#       network_interface_names: PedroBastionNIC
#       ssh_public_keys:
#       - path: /home/pedro/.ssh/authorized_keys
#         key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDpS16kB+yoDsbFdT93X5mfmrd+RYcJ/s8e/r/F8Q0i5mrCruIHPxFfy/Grekq1UZ8OyIRjW1tPg5KD1OC9ahJXWY+jaUCacBsM4c/RfPc4a2mn5oXoAF2YNOra9/3Us1y/Cx0Vq2Ie0Xjs07FqaXvticlroBCZ9c8PRmMBSNmsgTwm+Sbazs9KaPbg/M1XlgscqlG3SX6m9uI5s2FzpeK55jTfmECRWOIwlYmeRrz2h/9h2eKzjaQDxH3zjyoHiTJ2hgCN7ZQhc8DoQ4DBdKt01X6pL/HMnRlg8ojsQPkUxUENu858u25hx/pEFi3AqTDeGBA4Zxup0fVQetkkwSxV"
#       image:
#         offer: debian-10
#         publisher: Debian
#         sku: '10'
#         version: latest
#   - name: Get network interface details
#     azure_rm_networkinterface_facts:
#       resource_group: PedroTactile
#       name: PedroBastionNIC
#     register: azure_networkinterfaces
#     delegate_to: localhost

#   - name: Get facts for one network interface
#     azure_rm_networkinterface_info:
#       resource_group: PedroTactile
#       name: PedroBastionNIC
#     register: networkinterface_output

#   - name: set value of vm internal IP
#     set_fact:
#       vm_internal_ip: "{{ networkinterface_output.networkinterfaces[0].ip_configurations[0].private_ip_address}}"
#   - name: show private IP
#     debug: msg="{{ vm_internal_ip }}"<