- name: Create Azure panel container
  hosts: localhost
  connection: local
  tasks:
  - name: Get facts for all accounts in a resource group
    azure_rm_storageaccount_info:
      resource_group: PedroTactile
      name: pedrostorage
      show_connection_string: yes
    register: Pedrostorage
  - name: task debug
    debug:
      # msg: "{{ Pedrostorage }}"
      msg: "{{ Pedrostorage.storageaccounts[0].primary_endpoints.key }}"
  - name: Create sample container group
    azure_rm_containerinstance:
      resource_group: PedroTactile
      name: pedropanel
      os_type: linux
      ip_address: public
      dns_name_label: pedropanel
      restart_policy: always
      containers:
        - name: pedrocontainer
          image: aeonlucid/pterodactyl-panel
          cpu: 1
          memory: 1
          environment_variables:
            - name: PUID
              value: PUID=1000
            - name: PGID
              value: PGID=1000
            - name: creat_admin
              value: CREATE_ADMIN=yes
          volume_mounts:
            - name: pedrovolume
              mount_path: "/data"
          ports:
            - 8080
      volumes:
        - name: pedrovolume
          azure_file:
            storage_account_name: pedrostorage
            share_name: pedroshare
            storage_account_key: "{{ Pedrostorage.storageaccounts[0].primary_endpoints.key }}"