- name: Création VM Bastion
  hosts: localhost
  connection: local
  tasks:

  - name: Create VM
    azure_rm_virtualmachine:
      resource_group: testPedroTactile
      name: testPedroBastion
      vm_size: Standard_B1ls
      admin_username: pedro
      ssh_password_enabled: false
      network_interface_names: testPedroBastionNIC
      storage_account_name: testpedrostorage
      ssh_public_keys:
      - path: /home/pedro/.ssh/authorized_keys
        key_data: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDpS16kB+yoDsbFdT93X5mfmrd+RYcJ/s8e/r/F8Q0i5mrCruIHPxFfy/Grekq1UZ8OyIRjW1tPg5KD1OC9ahJXWY+jaUCacBsM4c/RfPc4a2mn5oXoAF2YNOra9/3Us1y/Cx0Vq2Ie0Xjs07FqaXvticlroBCZ9c8PRmMBSNmsgTwm+Sbazs9KaPbg/M1XlgscqlG3SX6m9uI5s2FzpeK55jTfmECRWOIwlYmeRrz2h/9h2eKzjaQDxH3zjyoHiTJ2hgCN7ZQhc8DoQ4DBdKt01X6pL/HMnRlg8ojsQPkUxUENu858u25hx/pEFi3AqTDeGBA4Zxup0fVQetkkwSxV"
      image:
        offer: debian-10
        publisher: Debian
        sku: '10'
        version: latest
      custom_data: "{{ lookup('file', '/home/alain/Documents/gitcloneb4/Simplon-Groupe2brief4/PedroTest/testinitBastion') }}"
  
  - name: Get network interface details
    azure_rm_networkinterface_facts:
      resource_group: testPedroTactile
      name: testPedroBastionNIC
    register: azure_networkinterfaces
    delegate_to: localhost

  - name: Get facts for one network interface
    azure_rm_networkinterface_info:
      resource_group: testPedroTactile
      name: testPedroBastionNIC
    register: networkinterface_output

  - name: set value of vm internal IP
    set_fact:
      vm_internal_ip: "{{ networkinterface_output.networkinterfaces[0].ip_configurations[0].private_ip_address}}"
  - name: show private IP
    debug: msg="{{ vm_internal_ip }}"<